name: Deploy static content to Pages

on:
    # Запускается при пуше в main ветку
    push:
        branches: ["main"]

    # Позволяет запускать workflow manually из вкладки Actions
    workflow_dispatch:

# Устанавливает разрешения для GITHUB_TOKEN чтобы разрешить деплой на Pages
permissions:
    contents: read
    pages: write
    id-token: write

# Позволяет только один concurrent deployment, пропуская runs в очереди между in-progress и latest queued
concurrency:
    group: "pages"
    cancel-in-progress: false

jobs:
    # Один job для деплоя
    deploy:
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "18"
                  cache: "npm"

            - name: Install dependencies
              run: npm ci

            - name: Build project
              run: npm run build

            - name: Setup Pages
              uses: actions/configure-pages@v4

            - name: Upload artifact
              uses: actions/upload-pages-artifact@v3
              with:
                  # Загружаем папку dist
                  path: "./dist"

            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
